/*
EN: DB/constant name at the top: DE_VERBS_MAIN — this file contains 36 verbs.
DE: DB-/Konstantenname am Anfang: DE_VERBS_MAIN — diese Datei enthält 36 Verben.
RU: Имя БД/константы в начале: DE_VERBS_MAIN — в этом файле 36 глаголов.
*/

// Auto-generated from old verb DB
const DE_VERBS_MAIN = [
  {
    inf: "gehen",
    voll: true,
    presens: {
      ich: "gehe",
      du: "gehst",
      er: "geht",
      wir: "gehen",
      ihr: "geht",
      sie: "gehen",
    },
    perfektAux: "sein",
    partizip: "gegangen",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "kommen",
    voll: true,
    presens: {
      ich: "komme",
      du: "kommst",
      er: "kommt",
      wir: "kommen",
      ihr: "kommt",
      sie: "kommen",
    },
    perfektAux: "sein",
    partizip: "gekommen",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "fahren",
    voll: true,
    presens: {
      ich: "fahre",
      du: "fährst",
      er: "fährt",
      wir: "fahren",
      ihr: "fahrt",
      sie: "fahren",
    },
    perfektAux: "sein",
    partizip: "gefahren",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "laufen",
    voll: true,
    presens: {
      ich: "laufe",
      du: "läufst",
      er: "läuft",
      wir: "laufen",
      ihr: "lauft",
      sie: "laufen",
    },
    perfektAux: "sein",
    partizip: "gelaufen",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "bleiben",
    voll: true,
    presens: {
      ich: "bleibe",
      du: "bleibst",
      er: "bleibt",
      wir: "bleiben",
      ihr: "bleibt",
      sie: "bleiben",
    },
    perfektAux: "sein",
    partizip: "geblieben",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "steigen",
    voll: true,
    presens: {
      ich: "steige",
      du: "steigst",
      er: "steigt",
      wir: "steigen",
      ihr: "steigt",
      sie: "steigen",
    },
    perfektAux: "sein",
    partizip: "gestiegen",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "machen",
    voll: true,
    presens: {
      ich: "mache",
      du: "machst",
      er: "macht",
      wir: "machen",
      ihr: "macht",
      sie: "machen",
    },
    perfektAux: "haben",
    partizip: "gemacht",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "arbeiten",
    voll: true,
    presens: {
      ich: "arbeite",
      du: "arbeitest",
      er: "arbeitet",
      wir: "arbeiten",
      ihr: "arbeitet",
      sie: "arbeiten",
    },
    perfektAux: "haben",
    partizip: "gearbeitet",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "lernen",
    voll: true,
    presens: {
      ich: "lerne",
      du: "lernst",
      er: "lernt",
      wir: "lernen",
      ihr: "lernt",
      sie: "lernen",
    },
    perfektAux: "haben",
    partizip: "gelernt",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "spielen",
    voll: true,
    presens: {
      ich: "spiele",
      du: "spielst",
      er: "spielt",
      wir: "spielen",
      ihr: "spielt",
      sie: "spielen",
    },
    perfektAux: "haben",
    partizip: "gespielt",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "essen",
    voll: true,
    presens: {
      ich: "esse",
      du: "isst",
      er: "isst",
      wir: "essen",
      ihr: "esst",
      sie: "essen",
    },
    perfektAux: "haben",
    partizip: "gegessen",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "trinken",
    voll: true,
    presens: {
      ich: "trinke",
      du: "trinkst",
      er: "trinkt",
      wir: "trinken",
      ihr: "trinkt",
      sie: "trinken",
    },
    perfektAux: "haben",
    partizip: "getrunken",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "schlafen",
    voll: true,
    presens: {
      ich: "schlafe",
      du: "schläfst",
      er: "schläft",
      wir: "schlafen",
      ihr: "schlaft",
      sie: "schlafen",
    },
    perfektAux: "haben",
    partizip: "geschlafen",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "kaufen",
    voll: true,
    presens: {
      ich: "kaufe",
      du: "kaufst",
      er: "kauft",
      wir: "kaufen",
      ihr: "kauft",
      sie: "kaufen",
    },
    perfektAux: "haben",
    partizip: "gekauft",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "bezahlen",
    voll: true,
    presens: {
      ich: "bezahle",
      du: "bezahlst",
      er: "bezahlt",
      wir: "bezahlen",
      ihr: "bezahlt",
      sie: "bezahlen",
    },
    perfektAux: "haben",
    partizip: "bezahlt",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "verkaufen",
    voll: true,
    presens: {
      ich: "verkaufe",
      du: "verkaufst",
      er: "verkauft",
      wir: "verkaufen",
      ihr: "verkauft",
      sie: "verkaufen",
    },
    perfektAux: "haben",
    partizip: "verkauft",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "geben",
    voll: true,
    presens: {
      ich: "gebe",
      du: "gibst",
      er: "gibt",
      wir: "geben",
      ihr: "gebt",
      sie: "geben",
    },
    perfektAux: "haben",
    partizip: "gegeben",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "nehmen",
    voll: true,
    presens: {
      ich: "nehme",
      du: "nimmst",
      er: "nimmt",
      wir: "nehmen",
      ihr: "nehmt",
      sie: "nehmen",
    },
    perfektAux: "haben",
    partizip: "genommen",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "bringen",
    voll: true,
    presens: {
      ich: "bringe",
      du: "bringst",
      er: "bringt",
      wir: "bringen",
      ihr: "bringt",
      sie: "bringen",
    },
    perfektAux: "haben",
    partizip: "gebracht",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "holen",
    voll: true,
    presens: {
      ich: "hole",
      du: "holst",
      er: "holt",
      wir: "holen",
      ihr: "holt",
      sie: "holen",
    },
    perfektAux: "haben",
    partizip: "geholt",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "sagen",
    voll: true,
    presens: {
      ich: "sage",
      du: "sagst",
      er: "sagt",
      wir: "sagen",
      ihr: "sagt",
      sie: "sagen",
    },
    perfektAux: "haben",
    partizip: "gesagt",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "sprechen",
    voll: true,
    presens: {
      ich: "spreche",
      du: "sprichst",
      er: "spricht",
      wir: "sprechen",
      ihr: "sprecht",
      sie: "sprechen",
    },
    perfektAux: "haben",
    partizip: "gesprochen",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "hören",
    voll: true,
    presens: {
      ich: "höre",
      du: "hörst",
      er: "hört",
      wir: "hören",
      ihr: "hört",
      sie: "hören",
    },
    perfektAux: "haben",
    partizip: "gehört",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "sehen",
    voll: true,
    presens: {
      ich: "sehe",
      du: "siehst",
      er: "sieht",
      wir: "sehen",
      ihr: "seht",
      sie: "sehen",
    },
    perfektAux: "haben",
    partizip: "gesehen",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "fragen",
    voll: true,
    presens: {
      ich: "frage",
      du: "fragst",
      er: "fragt",
      wir: "fragen",
      ihr: "fragt",
      sie: "fragen",
    },
    perfektAux: "haben",
    partizip: "gefragt",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "denken",
    voll: true,
    presens: {
      ich: "denke",
      du: "denkst",
      er: "denkt",
      wir: "denken",
      ihr: "denkt",
      sie: "denken",
    },
    perfektAux: "haben",
    partizip: "gedacht",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "glauben",
    voll: true,
    presens: {
      ich: "glaube",
      du: "glaubst",
      er: "glaubt",
      wir: "glauben",
      ihr: "glaubt",
      sie: "glauben",
    },
    perfektAux: "haben",
    partizip: "geglaubt",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "fühlen",
    voll: true,
    presens: {
      ich: "fühle",
      du: "fühlst",
      er: "fühlt",
      wir: "fühlen",
      ihr: "fühlt",
      sie: "fühlen",
    },
    perfektAux: "haben",
    partizip: "gefühlt",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "wissen",
    voll: true,
    presens: {
      ich: "weiß",
      du: "weißt",
      er: "weiß",
      wir: "wissen",
      ihr: "wisst",
      sie: "wissen",
    },
    perfektAux: "haben",
    partizip: "gewusst",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "helfen",
    voll: true,
    presens: {
      ich: "helfe",
      du: "hilfst",
      er: "hilft",
      wir: "helfen",
      ihr: "helft",
      sie: "helfen",
    },
    perfektAux: "haben",
    partizip: "geholfen",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "brauchen",
    voll: true,
    presens: {
      ich: "brauche",
      du: "brauchst",
      er: "braucht",
      wir: "brauchen",
      ihr: "braucht",
      sie: "brauchen",
    },
    perfektAux: "haben",
    partizip: "gebraucht",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "beginnen",
    voll: true,
    presens: {
      ich: "beginne",
      du: "beginnst",
      er: "beginnt",
      wir: "beginnen",
      ihr: "beginnt",
      sie: "beginnen",
    },
    perfektAux: "haben",
    partizip: "begonnen",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "enden",
    voll: true,
    presens: {
      ich: "ende",
      du: "endest",
      er: "endet",
      wir: "enden",
      ihr: "endet",
      sie: "enden",
    },
    perfektAux: "haben",
    partizip: "geendet",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "warten",
    voll: true,
    presens: {
      ich: "warte",
      du: "wartest",
      er: "wartet",
      wir: "warten",
      ihr: "wartet",
      sie: "warten",
    },
    perfektAux: "haben",
    partizip: "gewartet",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "wohnen",
    voll: true,
    presens: {
      ich: "wohne",
      du: "wohnst",
      er: "wohnt",
      wir: "wohnen",
      ihr: "wohnt",
      sie: "wohnen",
    },
    perfektAux: "haben",
    partizip: "gewohnt",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
  {
    inf: "putzen",
    voll: true,
    presens: {
      ich: "putze",
      du: "putzt",
      er: "putzt",
      wir: "putzen",
      ihr: "putzt",
      sie: "putzen",
    },
    perfektAux: "haben",
    partizip: "geputzt",
    trennbar: false,
    prefix: "",
    modal: false,
    reflexiv: false,
  },
];

// ------------------------------------------------------------
// DE: Präteritum-Formen für alle Verben
// EN: Preterite forms for all verbs
// RU: Формы претерита для всех глаголов
// ------------------------------------------------------------
const PRAETERITUM_FORMS = {
  gehen: {
    ich: "ging",
    du: "gingst",
    er_sie_es: "ging",
    wir: "gingen",
    ihr: "gingt",
    sie_Sie: "gingen",
  },
  kommen: {
    ich: "kam",
    du: "kamst",
    er_sie_es: "kam",
    wir: "kamen",
    ihr: "kamt",
    sie_Sie: "kamen",
  },
  fahren: {
    ich: "fuhr",
    du: "fuhrst",
    er_sie_es: "fuhr",
    wir: "fuhren",
    ihr: "fuhrt",
    sie_Sie: "fuhren",
  },
  laufen: {
    ich: "lief",
    du: "liefst",
    er_sie_es: "lief",
    wir: "liefen",
    ihr: "lieft",
    sie_Sie: "liefen",
  },
  bleiben: {
    ich: "blieb",
    du: "bliebst",
    er_sie_es: "blieb",
    wir: "blieben",
    ihr: "bliebt",
    sie_Sie: "blieben",
  },
  steigen: {
    ich: "stieg",
    du: "stiegst",
    er_sie_es: "stieg",
    wir: "stiegen",
    ihr: "stiegt",
    sie_Sie: "stiegen",
  },
  machen: {
    ich: "machte",
    du: "machtest",
    er_sie_es: "machte",
    wir: "machten",
    ihr: "machtet",
    sie_Sie: "machten",
  },
  arbeiten: {
    ich: "arbeitete",
    du: "arbeitetest",
    er_sie_es: "arbeitete",
    wir: "arbeiteten",
    ihr: "arbeitetet",
    sie_Sie: "arbeiteten",
  },
  lernen: {
    ich: "lernte",
    du: "lerntest",
    er_sie_es: "lernte",
    wir: "lernten",
    ihr: "lerntet",
    sie_Sie: "lernten",
  },
  spielen: {
    ich: "spielte",
    du: "spieltest",
    er_sie_es: "spielte",
    wir: "spielten",
    ihr: "spieltet",
    sie_Sie: "spielten",
  },
  essen: {
    ich: "aß",
    du: "aßest",
    er_sie_es: "aß",
    wir: "aßen",
    ihr: "aßt",
    sie_Sie: "aßen",
  },
  trinken: {
    ich: "trank",
    du: "trankst",
    er_sie_es: "trank",
    wir: "tranken",
    ihr: "trankt",
    sie_Sie: "tranken",
  },
  schlafen: {
    ich: "schlief",
    du: "schliefst",
    er_sie_es: "schlief",
    wir: "schliefen",
    ihr: "schlieft",
    sie_Sie: "schliefen",
  },
  kaufen: {
    ich: "kaufte",
    du: "kauftest",
    er_sie_es: "kaufte",
    wir: "kauften",
    ihr: "kauftet",
    sie_Sie: "kauften",
  },
  bezahlen: {
    ich: "bezahlte",
    du: "bezahltest",
    er_sie_es: "bezahlte",
    wir: "bezahlten",
    ihr: "bezahltet",
    sie_Sie: "bezahlten",
  },
  verkaufen: {
    ich: "verkaufte",
    du: "verkauftest",
    er_sie_es: "verkaufte",
    wir: "verkauften",
    ihr: "verkauftet",
    sie_Sie: "verkauften",
  },
  geben: {
    ich: "gab",
    du: "gabst",
    er_sie_es: "gab",
    wir: "gaben",
    ihr: "gabt",
    sie_Sie: "gaben",
  },
  nehmen: {
    ich: "nahm",
    du: "nahmst",
    er_sie_es: "nahm",
    wir: "nahmen",
    ihr: "nahmt",
    sie_Sie: "nahmen",
  },
  bringen: {
    ich: "brachte",
    du: "brachtest",
    er_sie_es: "brachte",
    wir: "brachten",
    ihr: "brachtet",
    sie_Sie: "brachten",
  },
  holen: {
    ich: "holte",
    du: "holtest",
    er_sie_es: "holte",
    wir: "holten",
    ihr: "holtet",
    sie_Sie: "holten",
  },
  sagen: {
    ich: "sagte",
    du: "sagtest",
    er_sie_es: "sagte",
    wir: "sagten",
    ihr: "sagtet",
    sie_Sie: "sagten",
  },
  sprechen: {
    ich: "sprach",
    du: "sprachst",
    er_sie_es: "sprach",
    wir: "sprachen",
    ihr: "spracht",
    sie_Sie: "sprachen",
  },
  hören: {
    ich: "hörte",
    du: "hörtest",
    er_sie_es: "hörte",
    wir: "hörten",
    ihr: "hörtet",
    sie_Sie: "hörten",
  },
  sehen: {
    ich: "sah",
    du: "sahst",
    er_sie_es: "sah",
    wir: "sahen",
    ihr: "saht",
    sie_Sie: "sahen",
  },
  fragen: {
    ich: "fragte",
    du: "fragtest",
    er_sie_es: "fragte",
    wir: "fragten",
    ihr: "fragtet",
    sie_Sie: "fragten",
  },
  denken: {
    ich: "dachte",
    du: "dachtest",
    er_sie_es: "dachte",
    wir: "dachten",
    ihr: "dachtet",
    sie_Sie: "dachten",
  },
  glauben: {
    ich: "glaubte",
    du: "glaubtest",
    er_sie_es: "glaubte",
    wir: "glaubten",
    ihr: "glaubtet",
    sie_Sie: "glaubten",
  },
  fühlen: {
    ich: "fühlte",
    du: "fühltest",
    er_sie_es: "fühlte",
    wir: "fühlten",
    ihr: "fühltet",
    sie_Sie: "fühlten",
  },
  wissen: {
    ich: "wusste",
    du: "wusstest",
    er_sie_es: "wusste",
    wir: "wussten",
    ihr: "wusstet",
    sie_Sie: "wussten",
  },
  helfen: {
    ich: "half",
    du: "halfst",
    er_sie_es: "half",
    wir: "halfen",
    ihr: "halft",
    sie_Sie: "halfen",
  },
  brauchen: {
    ich: "brauchte",
    du: "brauchtest",
    er_sie_es: "brauchte",
    wir: "brauchten",
    ihr: "brauchtet",
    sie_Sie: "brauchten",
  },
  beginnen: {
    ich: "begann",
    du: "begannst",
    er_sie_es: "begann",
    wir: "begannen",
    ihr: "begannt",
    sie_Sie: "begannen",
  },
  enden: {
    ich: "endete",
    du: "endetest",
    er_sie_es: "endete",
    wir: "endeten",
    ihr: "endetet",
    sie_Sie: "endeten",
  },
  warten: {
    ich: "wartete",
    du: "wartetest",
    er_sie_es: "wartete",
    wir: "warteten",
    ihr: "wartetet",
    sie_Sie: "warteten",
  },
  wohnen: {
    ich: "wohnte",
    du: "wohntest",
    er_sie_es: "wohnte",
    wir: "wohnten",
    ihr: "wohntet",
    sie_Sie: "wohnten",
  },
  putzen: {
    ich: "putzte",
    du: "putztest",
    er_sie_es: "putzte",
    wir: "putzten",
    ihr: "putztet",
    sie_Sie: "putzten",
  },
};

function normalizePraesens(p) {
  if (!p) return null;
  return {
    ich: p.ich || "",
    du: p.du || "",
    er_sie_es: p.er_sie_es || p.er || p.es || "",
    wir: p.wir || "",
    ihr: p.ihr || "",
    sie_Sie: p.sie_Sie || p.sie || p.Sie || "",
  };
}

// DE: Felder ergänzen und DE_VERBS-Objekt aufbauen
// EN: Enrich fields and build DE_VERBS object
// RU: Дополняем поля и строим объект DE_VERBS
const DE_VERBS = {};

DE_VERBS_MAIN.forEach((verb) => {
  verb.infinitiv = verb.infinitiv || verb.inf;
  verb.praesens = normalizePraesens(verb.praesens || verb.presens) || verb.praesens;
  verb.partizip2 = verb.partizip2 || verb.partizip;
  verb.usesSein = typeof verb.usesSein === "boolean" ? verb.usesSein : verb.perfektAux === "sein";
  verb.aux = verb.aux || verb.perfektAux;

  if (!verb.praeteritum && PRAETERITUM_FORMS[verb.inf]) {
    verb.praeteritum = PRAETERITUM_FORMS[verb.inf];
  }

  const key = verb.infinitiv || verb.inf;
  DE_VERBS[key] = verb;
});

if (typeof window !== "undefined") {
  window.DE_VERBS_MAIN = DE_VERBS_MAIN;
  window.DE_VERBS = DE_VERBS;
}
