// DE: Level-Datenbank (Demo) für Karten-Training
// EN: Level database (demo) for card training
// RU: Демонстрационная база уровней для тренировки карточек

const LG_KARTEN_LEVEL_DB = [
  // Level 1 – Begrüßung
  { id: "L1_001", level: 1, topic: "Begrüßung", de: "Hallo!", en: "Hello!", it: "Ciao!", fr: "Salut !", ru: "Привет!", es: "¡Hola!" },
  { id: "L1_002", level: 1, topic: "Begrüßung", de: "Guten Morgen!", en: "Good morning!", it: "Buongiorno!", fr: "Bonjour !", ru: "Доброе утро!", es: "¡Buenos días!" },
  { id: "L1_003", level: 1, topic: "Begrüßung", de: "Wie geht es dir?", en: "How are you?", it: "Come stai?", fr: "Comment ça va ?", ru: "Как дела?", es: "¿Cómo estás?" },
  { id: "L1_004", level: 1, topic: "Begrüßung", de: "Mir geht es gut, danke.", en: "I am fine, thank you.", it: "Sto bene, grazie.", fr: "Je vais bien, merci.", ru: "У меня всё хорошо, спасибо.", es: "Estoy bien, gracias." },
  { id: "L1_005", level: 1, topic: "Begrüßung", de: "Auf Wiedersehen!", en: "Goodbye!", it: "Arrivederci!", fr: "Au revoir !", ru: "До свидания!", es: "¡Adiós!" },

  // Level 2 – Persönliche Angaben
  {
    id: "L2_001",
    level: 2,
    topic: "Persönliche Angaben",
    de: "Ich heiße Thomas.",
    en: "My name is Thomas.",
    it: "Mi chiamo Thomas.",
    fr: "Je m'appelle Thomas.",
    ru: "Меня зовут Томас.",
    es: "Me llamo Thomas.",
  },
  {
    id: "L2_002",
    level: 2,
    topic: "Persönliche Angaben",
    de: "Ich komme aus Deutschland.",
    en: "I am from Germany.",
    it: "Vengo dalla Germania.",
    fr: "Je viens d'Allemagne.",
    ru: "Я из Германии.",
    es: "Soy de Alemania.",
  },
  {
    id: "L2_003",
    level: 2,
    topic: "Persönliche Angaben",
    de: "Ich wohne in Berlin.",
    en: "I live in Berlin.",
    it: "Vivo a Berlino.",
    fr: "J'habite à Berlin.",
    ru: "Я живу в Берлине.",
    es: "Vivo en Berlín.",
  },
  {
    id: "L2_004",
    level: 2,
    topic: "Persönliche Angaben",
    de: "Ich bin zwanzig Jahre alt.",
    en: "I am twenty years old.",
    it: "Ho vent'anni.",
    fr: "J'ai vingt ans.",
    ru: "Мне двадцать лет.",
    es: "Tengo veinte años.",
  },
  {
    id: "L2_005",
    level: 2,
    topic: "Persönliche Angaben",
    de: "Ich spreche ein wenig Englisch.",
    en: "I speak a little English.",
    it: "Parlo un po' di inglese.",
    fr: "Je parle un peu anglais.",
    ru: "Я немного говорю по-английски.",
    es: "Hablo un poco de inglés.",
  },

  // Level 3 – Reise
  {
    id: "L3_001",
    level: 3,
    topic: "Reise",
    de: "Wo ist der Bahnhof?",
    en: "Where is the train station?",
    it: "Dov'è la stazione?",
    fr: "Où est la gare ?",
    ru: "Где вокзал?",
    es: "¿Dónde está la estación de tren?",
  },
  {
    id: "L3_002",
    level: 3,
    topic: "Reise",
    de: "Wann fährt der nächste Zug nach Paris?",
    en: "When does the next train to Paris leave?",
    it: "Quando parte il prossimo treno per Parigi?",
    fr: "Quand part le prochain train pour Paris ?",
    ru: "Когда отправляется следующий поезд до Парижа?",
    es: "¿Cuándo sale el próximo tren a París?",
  },
  {
    id: "L3_003",
    level: 3,
    topic: "Reise",
    de: "Ich brauche ein Ticket nach München.",
    en: "I need a ticket to Munich.",
    it: "Ho bisogno di un biglietto per Monaco.",
    fr: "J'ai besoin d'un billet pour Munich.",
    ru: "Мне нужен билет до Мюнхена.",
    es: "Necesito un billete a Múnich.",
  },
  {
    id: "L3_004",
    level: 3,
    topic: "Reise",
    de: "Der Bus fährt alle zehn Minuten.",
    en: "The bus runs every ten minutes.",
    it: "L'autobus passa ogni dieci minuti.",
    fr: "Le bus passe toutes les dix minutes.",
    ru: "Автобус ходит каждые десять минут.",
    es: "El autobús pasa cada diez minutos.",
  },
  {
    id: "L3_005",
    level: 3,
    topic: "Reise",
    de: "Können Sie das auf der Karte zeigen?",
    en: "Can you show that on the map?",
    it: "Può mostrarmelo sulla mappa?",
    fr: "Pouvez-vous me montrer cela sur la carte ?",
    ru: "Можете показать это на карте?",
    es: "¿Puede mostrarlo en el mapa?",
  },
];
