// ==========================================================
// DE: Basis-Datenbank für Level-Karten mit 6 Sprachen
// EN: Base DB for level cards with 6 languages
// RU: Базовая БД для уровневых карточек с 6 языками
// ==========================================================
const LG_KARTEN_LEVEL_DB = [
  // Level 1 – Begrüßung / sehr einfach
  { id: "L1_001", level: 1, topic: "Begrüßung", de: "Hallo!", en: "Hello!", it: "Ciao!", fr: "Salut !", ru: "Привет!", es: "¡Hola!" },
  { id: "L1_002", level: 1, topic: "Begrüßung", de: "Guten Morgen!", en: "Good morning!", it: "Buongiorno!", fr: "Bonjour !", ru: "Доброе утро!", es: "¡Buenos días!" },
  { id: "L1_003", level: 1, topic: "Begrüßung", de: "Guten Abend!", en: "Good evening!", it: "Buonasera!", fr: "Bonsoir !", ru: "Добрый вечер!", es: "¡Buenas noches!" },
  { id: "L1_004", level: 1, topic: "Begrüßung", de: "Wie geht es dir?", en: "How are you?", it: "Come stai?", fr: "Comment ça va ?", ru: "Как дела?", es: "¿Cómo estás?" },
  { id: "L1_005", level: 1, topic: "Begrüßung", de: "Mir geht es gut.", en: "I am fine.", it: "Sto bene.", fr: "Je vais bien.", ru: "У меня всё хорошо.", es: "Estoy bien." },
  { id: "L1_006", level: 1, topic: "Begrüßung", de: "Danke!", en: "Thank you!", it: "Grazie!", fr: "Merci !", ru: "Спасибо!", es: "¡Gracias!" },
  { id: "L1_007", level: 1, topic: "Begrüßung", de: "Bitte.", en: "Please.", it: "Per favore.", fr: "S'il vous plaît.", ru: "Пожалуйста.", es: "Por favor." },
  { id: "L1_008", level: 1, topic: "Begrüßung", de: "Ja.", en: "Yes.", it: "Sì.", fr: "Oui.", ru: "Да.", es: "Sí." },
  { id: "L1_009", level: 1, topic: "Begrüßung", de: "Nein.", en: "No.", it: "No.", fr: "Non.", ru: "Нет.", es: "No." },
  { id: "L1_010", level: 1, topic: "Begrüßung", de: "Ich heiße Anna.", en: "My name is Anna.", it: "Mi chiamo Anna.", fr: "Je m'appelle Anna.", ru: "Меня зовут Анна.", es: "Me llamo Ana." },

  // Level 2 – Persönliche Angaben
  { id: "L2_011", level: 2, topic: "Persönliche Angaben", de: "Ich komme aus Deutschland.", en: "I am from Germany.", it: "Vengo dalla Germania.", fr: "Je viens d'Allemagne.", ru: "Я из Германии.", es: "Soy de Alemania." },
  { id: "L2_012", level: 2, topic: "Persönliche Angaben", de: "Ich wohne in Berlin.", en: "I live in Berlin.", it: "Vivo a Berlino.", fr: "J'habite à Berlin.", ru: "Я живу в Берлине.", es: "Vivo en Berlín." },
  { id: "L2_013", level: 2, topic: "Persönliche Angaben", de: "Ich bin dreißig Jahre alt.", en: "I am thirty years old.", it: "Ho trent'anni.", fr: "J'ai trente ans.", ru: "Мне тридцать лет.", es: "Tengo treinta años." },
  { id: "L2_014", level: 2, topic: "Persönliche Angaben", de: "Ich spreche ein wenig Englisch.", en: "I speak a little English.", it: "Parlo un po' di inglese.", fr: "Je parle un peu anglais.", ru: "Я немного говорю по-английски.", es: "Hablo un poco de inglés." },
  { id: "L2_015", level: 2, topic: "Persönliche Angaben", de: "Ich lerne Italienisch.", en: "I am learning Italian.", it: "Sto imparando l'italiano.", fr: "J'apprends l'italien.", ru: "Я учу итальянский.", es: "Estoy aprendiendo italiano." },
  { id: "L2_016", level: 2, topic: "Persönliche Angaben", de: "Ich arbeite als Ingenieur.", en: "I work as an engineer.", it: "Lavoro come ingegnere.", fr: "Je travaille comme ingénieur.", ru: "Я работаю инженером.", es: "Trabajo como ingeniero." },
  { id: "L2_017", level: 2, topic: "Persönliche Angaben", de: "Ich habe zwei Geschwister.", en: "I have two siblings.", it: "Ho due fratelli.", fr: "J'ai deux frères et sœurs.", ru: "У меня двое братьев и сестер.", es: "Tengo dos hermanos." },
  { id: "L2_018", level: 2, topic: "Persönliche Angaben", de: "Ich bin verheiratet.", en: "I am married.", it: "Sono sposato/a.", fr: "Je suis marié(e).", ru: "Я женат / я замужем.", es: "Estoy casado/a." },
  { id: "L2_019", level: 2, topic: "Persönliche Angaben", de: "Ich habe ein Kind.", en: "I have one child.", it: "Ho un figlio.", fr: "J'ai un enfant.", ru: "У меня есть ребенок.", es: "Tengo un hijo." },
  { id: "L2_020", level: 2, topic: "Persönliche Angaben", de: "Ich studiere an der Universität.", en: "I study at the university.", it: "Studio all'università.", fr: "J'étudie à l'université.", ru: "Я учусь в университете.", es: "Estudio en la universidad." },

  // Level 3 – Orientierung / Wegbeschreibung
  { id: "L3_021", level: 3, topic: "Orientierung", de: "Wo ist der Bahnhof?", en: "Where is the train station?", it: "Dov'è la stazione?", fr: "Où est la gare ?", ru: "Где вокзал?", es: "¿Dónde está la estación?" },
  { id: "L3_022", level: 3, topic: "Orientierung", de: "Gehen Sie bitte geradeaus.", en: "Please go straight ahead.", it: "Vada dritto, per favore.", fr: "Allez tout droit, s'il vous plaît.", ru: "Идите, пожалуйста, прямо.", es: "Vaya todo recto, por favor." },
  { id: "L3_023", level: 3, topic: "Orientierung", de: "Biegen Sie links ab.", en: "Turn left.", it: "Giri a sinistra.", fr: "Tournez à gauche.", ru: "Поверните налево.", es: "Gire a la izquierda." },
  { id: "L3_024", level: 3, topic: "Orientierung", de: "Es ist in der Nähe.", en: "It is nearby.", it: "È qui vicino.", fr: "C'est tout près.", ru: "Это рядом.", es: "Está cerca." },
  { id: "L3_025", level: 3, topic: "Orientierung", de: "Wie komme ich zum Zentrum?", en: "How do I get to the center?", it: "Come arrivo al centro?", fr: "Comment aller au centre ?", ru: "Как добраться до центра?", es: "¿Cómo llego al centro?" },
  { id: "L3_026", level: 3, topic: "Orientierung", de: "Gibt es eine U-Bahn hier?", en: "Is there a metro here?", it: "C'è una metro qui?", fr: "Y a-t-il un métro ici ?", ru: "Здесь есть метро?", es: "¿Hay metro aquí?" },
  { id: "L3_027", level: 3, topic: "Orientierung", de: "Die Straße ist gesperrt.", en: "The street is closed.", it: "La strada è chiusa.", fr: "La rue est fermée.", ru: "Улица перекрыта.", es: "La calle está cortada." },
  { id: "L3_028", level: 3, topic: "Orientierung", de: "Nehmen Sie den Bus Nummer zehn.", en: "Take bus number ten.", it: "Prenda l'autobus numero dieci.", fr: "Prenez le bus numéro dix.", ru: "Возьмите автобус номер десять.", es: "Tome el autobús número diez." },
  { id: "L3_029", level: 3, topic: "Orientierung", de: "Die Haltestelle ist dort drüben.", en: "The stop is over there.", it: "La fermata è laggiù.", fr: "L'arrêt est là-bas.", ru: "Остановка вон там.", es: "La parada está allí." },
  { id: "L3_030", level: 3, topic: "Orientierung", de: "Brauche ich ein Ticket vorher?", en: "Do I need a ticket in advance?", it: "Serve un biglietto prima?", fr: "Faut-il un billet à l'avance ?", ru: "Нужно билет заранее?", es: "¿Necesito un billete por adelantado?" },

  // Level 4 – Essen & Trinken / Restaurant
  { id: "L4_031", level: 4, topic: "Restaurant", de: "Haben Sie einen Tisch für zwei?", en: "Do you have a table for two?", it: "Avete un tavolo per due?", fr: "Avez-vous une table pour deux ?", ru: "У вас есть столик на двоих?", es: "¿Tienen una mesa para dos?" },
  { id: "L4_032", level: 4, topic: "Restaurant", de: "Ich möchte die Speisekarte sehen.", en: "I would like to see the menu.", it: "Vorrei vedere il menù.", fr: "Je voudrais voir la carte.", ru: "Я хотел бы увидеть меню.", es: "Quisiera ver el menú." },
  { id: "L4_033", level: 4, topic: "Restaurant", de: "Können Sie etwas empfehlen?", en: "Can you recommend something?", it: "Può consigliare qualcosa?", fr: "Pouvez-vous recommander quelque chose ?", ru: "Можете что-то посоветовать?", es: "¿Puede recomendar algo?" },
  { id: "L4_034", level: 4, topic: "Restaurant", de: "Ich bin allergisch gegen Nüsse.", en: "I am allergic to nuts.", it: "Sono allergico/a alle noci.", fr: "Je suis allergique aux noix.", ru: "У меня аллергия на орехи.", es: "Soy alérgico/a a los frutos secos." },
  { id: "L4_035", level: 4, topic: "Restaurant", de: "Ohne Fleisch, bitte.", en: "Without meat, please.", it: "Senza carne, per favore.", fr: "Sans viande, s'il vous plaît.", ru: "Без мяса, пожалуйста.", es: "Sin carne, por favor." },
  { id: "L4_036", level: 4, topic: "Restaurant", de: "Ich nehme ein Wasser ohne Kohlensäure.", en: "I'll have still water.", it: "Prendo un'acqua naturale.", fr: "Je prends de l'eau plate.", ru: "Я возьму негазированную воду.", es: "Tomaré agua sin gas." },
  { id: "L4_037", level: 4, topic: "Restaurant", de: "Die Rechnung, bitte.", en: "The bill, please.", it: "Il conto, per favore.", fr: "L'addition, s'il vous plaît.", ru: "Счёт, пожалуйста.", es: "La cuenta, por favor." },
  { id: "L4_038", level: 4, topic: "Restaurant", de: "Stimmt so, danke.", en: "Keep the change, thanks.", it: "Tenga il resto, grazie.", fr: "Gardez la monnaie, merci.", ru: "Сдачу оставьте себе, спасибо.", es: "Quédese con el cambio, gracias." },
  { id: "L4_039", level: 4, topic: "Restaurant", de: "Schmeckt sehr gut!", en: "It tastes very good!", it: "È molto buono!", fr: "C'est très bon !", ru: "Очень вкусно!", es: "¡Sabe muy bien!" },
  { id: "L4_040", level: 4, topic: "Restaurant", de: "Ist das Gericht scharf?", en: "Is the dish spicy?", it: "Il piatto è piccante?", fr: "Le plat est-il épicé ?", ru: "Блюдо острое?", es: "¿El plato es picante?" },

  // Level 5 – Alltag / Einkaufen / Uhrzeit
  { id: "L5_041", level: 5, topic: "Alltag", de: "Wie spät ist es jetzt?", en: "What time is it now?", it: "Che ore sono adesso?", fr: "Quelle heure est-il maintenant ?", ru: "Который сейчас час?", es: "¿Qué hora es ahora?" },
  { id: "L5_042", level: 5, topic: "Einkaufen", de: "Wie viel kostet das?", en: "How much does this cost?", it: "Quanto costa questo?", fr: "Combien ça coûte ?", ru: "Сколько это стоит?", es: "¿Cuánto cuesta esto?" },
  { id: "L5_043", level: 5, topic: "Einkaufen", de: "Haben Sie das in einer anderen Größe?", en: "Do you have this in another size?", it: "Ce l'avete in un'altra taglia?", fr: "L'avez-vous dans une autre taille ?", ru: "У вас есть это другого размера?", es: "¿Lo tiene en otra talla?" },
  { id: "L5_044", level: 5, topic: "Alltag", de: "Ich muss noch einkaufen gehen.", en: "I still need to go shopping.", it: "Devo ancora andare a fare la spesa.", fr: "Je dois encore faire des courses.", ru: "Мне ещё нужно сходить за покупками.", es: "Aún tengo que ir de compras." },
  { id: "L5_045", level: 5, topic: "Alltag", de: "Der Bus kommt in zehn Minuten.", en: "The bus arrives in ten minutes.", it: "L'autobus arriva tra dieci minuti.", fr: "Le bus arrive dans dix minutes.", ru: "Автобус приедет через десять минут.", es: "El autobús llega en diez minutos." },
  { id: "L5_046", level: 5, topic: "Alltag", de: "Kannst du mir kurz helfen?", en: "Can you help me quickly?", it: "Puoi aiutarmi un attimo?", fr: "Peux-tu m'aider un instant ?", ru: "Ты можешь мне быстро помочь?", es: "¿Puedes ayudarme un momento?" },
  { id: "L5_047", level: 5, topic: "Einkaufen", de: "Ich zahle bar.", en: "I pay in cash.", it: "Pago in contanti.", fr: "Je paie en espèces.", ru: "Я плачу наличными.", es: "Pago en efectivo." },
  { id: "L5_048", level: 5, topic: "Einkaufen", de: "Kann ich mit Karte zahlen?", en: "Can I pay by card?", it: "Posso pagare con la carta?", fr: "Puis-je payer par carte ?", ru: "Можно оплатить картой?", es: "¿Puedo pagar con tarjeta?" },
  { id: "L5_049", level: 5, topic: "Alltag", de: "Ich habe heute viel zu tun.", en: "I have a lot to do today.", it: "Ho molto da fare oggi.", fr: "J'ai beaucoup à faire aujourd'hui.", ru: "Мне сегодня нужно много сделать.", es: "Tengo mucho que hacer hoy." },
  { id: "L5_050", level: 5, topic: "Alltag", de: "Ich schreibe alles in meinen Kalender.", en: "I write everything in my calendar.", it: "Scrivo tutto nel mio calendario.", fr: "J'écris tout dans mon agenda.", ru: "Я записываю всё в свой календарь.", es: "Lo apunto todo en mi calendario." },

  // Level 6 – Reise & Unterkunft
  { id: "L6_051", level: 6, topic: "Reise", de: "Ich habe ein Ticket für den Zug um neun.", en: "I have a ticket for the train at nine.", it: "Ho un biglietto per il treno alle nove.", fr: "J'ai un billet pour le train de neuf heures.", ru: "У меня билет на поезд в девять.", es: "Tengo un billete para el tren a las nueve." },
  { id: "L6_052", level: 6, topic: "Reise", de: "Der Flug hat Verspätung.", en: "The flight is delayed.", it: "Il volo è in ritardo.", fr: "Le vol est retardé.", ru: "Рейс задерживается.", es: "El vuelo está retrasado." },
  { id: "L6_053", level: 6, topic: "Reise", de: "Wo ist die Gepäckausgabe?", en: "Where is the baggage claim?", it: "Dov'è il ritiro bagagli?", fr: "Où est la récupération des bagages ?", ru: "Где выдача багажа?", es: "¿Dónde está la recogida de equipaje?" },
  { id: "L6_054", level: 6, topic: "Unterkunft", de: "Ich habe eine Reservierung auf den Namen Meyer.", en: "I have a reservation under the name Meyer.", it: "Ho una prenotazione a nome Meyer.", fr: "J'ai une réservation au nom de Meyer.", ru: "У меня бронь на фамилию Майер.", es: "Tengo una reserva a nombre de Meyer." },
  { id: "L6_055", level: 6, topic: "Unterkunft", de: "Gibt es WLAN im Zimmer?", en: "Is there Wi‑Fi in the room?", it: "C'è il Wi‑Fi in camera?", fr: "Y a-t-il du Wi‑Fi dans la chambre ?", ru: "Есть ли Wi‑Fi в номере?", es: "¿Hay Wi‑Fi en la habitación?" },
  { id: "L6_056", level: 6, topic: "Unterkunft", de: "Das Zimmer ist zu kalt.", en: "The room is too cold.", it: "La stanza è troppo fredda.", fr: "La chambre est trop froide.", ru: "Комната слишком холодная.", es: "La habitación está demasiado fría." },
  { id: "L6_057", level: 6, topic: "Unterkunft", de: "Können Sie ein Taxi bestellen?", en: "Could you order a taxi?", it: "Può chiamare un taxi?", fr: "Pouvez-vous appeler un taxi ?", ru: "Можете вызвать такси?", es: "¿Puede pedir un taxi?" },
  { id: "L6_058", level: 6, topic: "Reise", de: "Ich möchte einen Fensterplatz.", en: "I would like a window seat.", it: "Vorrei un posto al finestrino.", fr: "Je voudrais une place près de la fenêtre.", ru: "Я бы хотел место у окна.", es: "Quisiera un asiento de ventana." },
  { id: "L6_059", level: 6, topic: "Reise", de: "Wann fährt der nächste Zug nach Paris?", en: "When does the next train to Paris leave?", it: "Quando parte il prossimo treno per Parigi?", fr: "Quand part le prochain train pour Paris ?", ru: "Когда идёт следующий поезд до Парижа?", es: "¿Cuándo sale el próximo tren a París?" },
  { id: "L6_060", level: 6, topic: "Unterkunft", de: "Ich bleibe drei Nächte.", en: "I am staying three nights.", it: "Rimango tre notti.", fr: "Je reste trois nuits.", ru: "Я остаюсь на три ночи.", es: "Me quedo tres noches." },

  // Level 7 – Gesundheit / Arzt / Apotheke
  { id: "L7_061", level: 7, topic: "Gesundheit", de: "Ich habe Kopfschmerzen.", en: "I have a headache.", it: "Ho mal di testa.", fr: "J'ai mal à la tête.", ru: "У меня болит голова.", es: "Tengo dolor de cabeza." },
  { id: "L7_062", level: 7, topic: "Gesundheit", de: "Mir ist schwindelig.", en: "I feel dizzy.", it: "Mi gira la testa.", fr: "J'ai la tête qui tourne.", ru: "У меня кружится голова.", es: "Me siento mareado/a." },
  { id: "L7_063", level: 7, topic: "Gesundheit", de: "Haben Sie etwas gegen Fieber?", en: "Do you have something for fever?", it: "Avete qualcosa contro la febbre?", fr: "Avez-vous quelque chose contre la fièvre ?", ru: "У вас есть что-то от температуры?", es: "¿Tiene algo para la fiebre?" },
  { id: "L7_064", level: 7, topic: "Gesundheit", de: "Ich brauche einen Arzt.", en: "I need a doctor.", it: "Ho bisogno di un medico.", fr: "J'ai besoin d'un médecin.", ru: "Мне нужен врач.", es: "Necesito un médico." },
  { id: "L7_065", level: 7, topic: "Gesundheit", de: "Ich habe mich verletzt.", en: "I hurt myself.", it: "Mi sono ferito/a.", fr: "Je me suis blessé(e).", ru: "Я поранился.", es: "Me he herido." },
  { id: "L7_066", level: 7, topic: "Gesundheit", de: "Wo ist die nächste Apotheke?", en: "Where is the nearest pharmacy?", it: "Dov'è la farmacia più vicina?", fr: "Où est la pharmacie la plus proche ?", ru: "Где ближайшая аптека?", es: "¿Dónde está la farmacia más cercana?" },
  { id: "L7_067", level: 7, topic: "Gesundheit", de: "Ich habe eine Allergie gegen Penicillin.", en: "I am allergic to penicillin.", it: "Sono allergico/a alla penicillina.", fr: "Je suis allergique à la pénicilline.", ru: "У меня аллергия на пенициллин.", es: "Soy alérgico/a a la penicilina." },
  { id: "L7_068", level: 7, topic: "Gesundheit", de: "Ich brauche Schmerzmittel.", en: "I need painkillers.", it: "Ho bisogno di antidolorifici.", fr: "J'ai besoin d'analgésiques.", ru: "Мне нужны обезболивающие.", es: "Necesito analgésicos." },
  { id: "L7_069", level: 7, topic: "Gesundheit", de: "Ich habe Fieber seit gestern.", en: "I have had a fever since yesterday.", it: "Ho la febbre da ieri.", fr: "J'ai de la fièvre depuis hier.", ru: "У меня температура со вчера.", es: "Tengo fiebre desde ayer." },
  { id: "L7_070", level: 7, topic: "Gesundheit", de: "Kann ich einen Termin bekommen?", en: "Can I get an appointment?", it: "Posso avere un appuntamento?", fr: "Puis-je obtenir un rendez-vous ?", ru: "Могу записаться на приём?", es: "¿Puedo conseguir una cita?" },

  // Level 8 – Probleme / Reklamation / Hilfe
  { id: "L8_071", level: 8, topic: "Probleme", de: "Mein Gepäck ist verloren gegangen.", en: "My luggage is lost.", it: "Il mio bagaglio è stato smarrito.", fr: "Mes bagages ont été perdus.", ru: "Мой багаж потерялся.", es: "Mi equipaje se ha perdido." },
  { id: "L8_072", level: 8, topic: "Probleme", de: "Die Klimaanlage funktioniert nicht.", en: "The air conditioning is not working.", it: "L'aria condizionata non funziona.", fr: "La climatisation ne marche pas.", ru: "Кондиционер не работает.", es: "El aire acondicionado no funciona." },
  { id: "L8_073", level: 8, topic: "Probleme", de: "Ich möchte eine Beschwerde einreichen.", en: "I want to file a complaint.", it: "Vorrei fare un reclamo.", fr: "Je veux déposer une plainte.", ru: "Я хочу подать жалобу.", es: "Quiero presentar una queja." },
  { id: "L8_074", level: 8, topic: "Probleme", de: "Können Sie mir bitte helfen?", en: "Could you please help me?", it: "Potrebbe aiutarmi, per favore?", fr: "Pourriez-vous m'aider, s'il vous plaît ?", ru: "Не могли бы вы мне помочь?", es: "¿Podría ayudarme, por favor?" },
  { id: "L8_075", level: 8, topic: "Probleme", de: "Das ist nicht, was ich bestellt habe.", en: "This is not what I ordered.", it: "Non è ciò che ho ordinato.", fr: "Ce n'est pas ce que j'ai commandé.", ru: "Это не то, что я заказывал.", es: "Esto no es lo que pedí." },
  { id: "L8_076", level: 8, topic: "Probleme", de: "Ich habe die falsche Rechnung bekommen.", en: "I received the wrong bill.", it: "Ho ricevuto il conto sbagliato.", fr: "J'ai reçu la mauvaise facture.", ru: "Мне дали неправильный счёт.", es: "He recibido la factura equivocada." },
  { id: "L8_077", level: 8, topic: "Probleme", de: "Bitte schicken Sie jemanden vorbei.", en: "Please send someone over.", it: "Per favore mandi qualcuno.", fr: "Veuillez envoyer quelqu'un.", ru: "Пожалуйста, пришлите кого-нибудь.", es: "Por favor envíe a alguien." },
  { id: "L8_078", level: 8, topic: "Probleme", de: "Ich habe meine Schlüssel verloren.", en: "I lost my keys.", it: "Ho perso le chiavi.", fr: "J'ai perdu mes clés.", ru: "Я потерял ключи.", es: "Perdí mis llaves." },
  { id: "L8_079", level: 8, topic: "Probleme", de: "Das Internet ist sehr langsam.", en: "The internet is very slow.", it: "Internet è molto lento.", fr: "Internet est très lent.", ru: "Интернет очень медленный.", es: "Internet es muy lento." },
  { id: "L8_080", level: 8, topic: "Probleme", de: "Ich brauche sofort Hilfe.", en: "I need help immediately.", it: "Ho bisogno di aiuto subito.", fr: "J'ai besoin d'aide immédiatement.", ru: "Мне нужна помощь немедленно.", es: "Necesito ayuda de inmediato." },

  // Level 9 – Meinung / einfache Begründungen
  { id: "L9_081", level: 9, topic: "Meinung", de: "Ich finde, das ist eine gute Idee.", en: "I think this is a good idea.", it: "Penso che sia una buona idea.", fr: "Je pense que c'est une bonne idée.", ru: "Я считаю, это хорошая идея.", es: "Creo que es una buena idea." },
  { id: "L9_082", level: 9, topic: "Meinung", de: "Meiner Meinung nach sollten wir warten.", en: "In my opinion we should wait.", it: "Secondo me dovremmo aspettare.", fr: "À mon avis, nous devrions attendre.", ru: "По моему мнению, нам стоит подождать.", es: "En mi opinión, deberíamos esperar." },
  { id: "L9_083", level: 9, topic: "Meinung", de: "Ich stimme dir zu.", en: "I agree with you.", it: "Sono d'accordo con te.", fr: "Je suis d'accord avec toi.", ru: "Я с тобой согласен.", es: "Estoy de acuerdo contigo." },
  { id: "L9_084", level: 9, topic: "Meinung", de: "Ich bin damit nicht einverstanden.", en: "I do not agree with that.", it: "Non sono d'accordo con questo.", fr: "Je ne suis pas d'accord avec ça.", ru: "Я с этим не согласен.", es: "No estoy de acuerdo con eso." },
  { id: "L9_085", level: 9, topic: "Meinung", de: "Das ist nur meine Einschätzung.", en: "That is just my assessment.", it: "È solo la mia valutazione.", fr: "C'est juste mon appréciation.", ru: "Это лишь моя оценка.", es: "Esa es solo mi valoración." },
  { id: "L9_086", level: 9, topic: "Meinung", de: "Wir brauchen mehr Informationen.", en: "We need more information.", it: "Abbiamo bisogno di più informazioni.", fr: "Nous avons besoin de plus d'informations.", ru: "Нам нужно больше информации.", es: "Necesitamos más información." },
  { id: "L9_087", level: 9, topic: "Meinung", de: "Können wir das genauer prüfen?", en: "Can we examine this more closely?", it: "Possiamo esaminarlo più da vicino?", fr: "Pouvons-nous examiner cela de plus près ?", ru: "Можем рассмотреть это внимательнее?", es: "¿Podemos examinar esto más de cerca?" },
  { id: "L9_088", level: 9, topic: "Meinung", de: "Ich denke, das ist machbar.", en: "I think this is feasible.", it: "Penso che sia fattibile.", fr: "Je pense que c'est faisable.", ru: "Думаю, это осуществимо.", es: "Creo que esto es viable." },
  { id: "L9_089", level: 9, topic: "Meinung", de: "Wir sollten die Risiken bedenken.", en: "We should consider the risks.", it: "Dovremmo considerare i rischi.", fr: "Nous devrions considérer les risques.", ru: "Нам следует учитывать риски.", es: "Deberíamos considerar los riesgos." },
  { id: "L9_090", level: 9, topic: "Meinung", de: "Es wäre besser, einen Plan B zu haben.", en: "It would be better to have a plan B.", it: "Sarebbe meglio avere un piano B.", fr: "Ce serait mieux d'avoir un plan B.", ru: "Лучше иметь план Б.", es: "Sería mejor tener un plan B." },

  // Level 10 – längere, aber praxisnahe Sätze
  { id: "L10_091", level: 10, topic: "Sonstiges", de: "Wir sollten alle Beteiligten früh informieren, um Probleme zu vermeiden.", en: "We should inform all stakeholders early to avoid problems.", it: "Dovremmo informare presto tutti gli interessati per evitare problemi.", fr: "Nous devrions informer tôt toutes les parties pour éviter des problèmes.", ru: "Нам стоит рано информировать всех участников, чтобы избежать проблем.", es: "Deberíamos informar temprano a todas las partes para evitar problemas." },
  { id: "L10_092", level: 10, topic: "Sonstiges", de: "Bitte priorisiere die Aufgaben nach Wichtigkeit und Aufwand.", en: "Please prioritize the tasks by importance and effort.", it: "Per favore dai priorità ai compiti per importanza e sforzo.", fr: "Merci de prioriser les tâches par importance et effort.", ru: "Пожалуйста, расставь приоритеты задач по важности и усилиям.", es: "Por favor prioriza las tareas por importancia y esfuerzo." },
  { id: "L10_093", level: 10, topic: "Reise", de: "Wir sollten einen Plan B vorbereiten, falls der Flug ausfällt.", en: "We should prepare a plan B in case the flight is cancelled.", it: "Dovremmo preparare un piano B se il volo viene cancellato.", fr: "Nous devrions préparer un plan B au cas où le vol serait annulé.", ru: "Нам стоит подготовить план Б на случай отмены рейса.", es: "Deberíamos preparar un plan B por si se cancela el vuelo." },
  { id: "L10_094", level: 10, topic: "Gesundheit", de: "Wir machen zusätzliche Tests, um die Qualität zu sichern.", en: "We run additional tests to ensure quality.", it: "Facciamo test aggiuntivi per garantire la qualità.", fr: "Nous faisons des tests supplémentaires pour garantir la qualité.", ru: "Мы проводим дополнительные тесты, чтобы обеспечить качество.", es: "Realizamos pruebas adicionales para asegurar la calidad." },
  { id: "L10_095", level: 10, topic: "Probleme", de: "Halte bitte alle Ergebnisse in einem kurzen Protokoll fest.", en: "Please record all results in a short report.", it: "Per favore registra tutti i risultati in un breve verbale.", fr: "Merci de consigner tous les résultats dans un bref compte rendu.", ru: "Пожалуйста, зафиксируй все результаты в коротком протоколе.", es: "Por favor registra todos los resultados en un breve informe." },
  { id: "L10_096", level: 10, topic: "Meinung", de: "Wir müssen Einsparungen finden, ohne die Ziele zu gefährden.", en: "We need to find savings without endangering the goals.", it: "Dobbiamo trovare risparmi senza mettere a rischio gli obiettivi.", fr: "Nous devons trouver des économies sans mettre en danger les objectifs.", ru: "Нужно найти экономию, не ставя цели под угрозу.", es: "Debemos encontrar ahorros sin poner en riesgo los objetivos." },
  { id: "L10_097", level: 10, topic: "Sonstiges", de: "Formuliere die Bedingungen klar, bevor wir unterschreiben.", en: "State the terms clearly before we sign.", it: "Formula chiaramente le condizioni prima di firmare.", fr: "Formule clairement les conditions avant de signer.", ru: "Сформулируй условия ясно, прежде чем подписывать.", es: "Formula claramente las condiciones antes de firmar." },
  { id: "L10_098", level: 10, topic: "Reise", de: "Wir starten mit einem Pilotprojekt, um das Konzept zu testen.", en: "We start with a pilot project to test the concept.", it: "Iniziamo con un progetto pilota per testare il concetto.", fr: "Nous commençons par un projet pilote pour tester le concept.", ru: "Мы начнём с пилотного проекта, чтобы проверить концепцию.", es: "Comenzamos con un proyecto piloto para probar el concepto." },
  { id: "L10_099", level: 10, topic: "Sonstiges", de: "Alle Änderungen werden in einem gemeinsamen Dokument festgehalten.", en: "All changes are recorded in a shared document.", it: "Tutte le modifiche sono registrate in un documento condiviso.", fr: "Toutes les modifications sont consignées dans un document partagé.", ru: "Все изменения фиксируются в общем документе.", es: "Todos los cambios se registran en un documento compartido." },
  { id: "L10_100", level: 10, topic: "Sonstiges", de: "Nach Abschluss teilen wir die Ergebnisse mit allen Beteiligten.", en: "After completion we share the results with all stakeholders.", it: "Dopo il completamento condividiamo i risultati con tutti gli interessati.", fr: "Après la fin, nous partageons les résultats avec toutes les parties.", ru: "После завершения мы поделимся результатами со всеми участниками.", es: "Al finalizar compartiremos los resultados con todas las partes." },
];

// Stellt sicher, dass die DB auch über window verfügbar ist
if (typeof window !== "undefined") {
  window.LG_KARTEN_LEVEL_DB = LG_KARTEN_LEVEL_DB;
}
